"""Added Transactions Model

Revision ID: 1ee31e72567f
Revises: 893c5f820bbf
Create Date: 2024-05-08 18:25:16.764103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from lib.utils.constants.transactions import TransactionStatus

# revision identifiers, used by Alembic.
revision: str = "1ee31e72567f"
down_revision: Union[str, None] = "893c5f820bbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS blockchain")
    op.create_table(
        "transactions",
        sa.Column("id", sa.String(256), primary_key=True, nullable=False),
        sa.Column("transaction_id", sa.String(256), nullable=False),
        sa.Column(
            "sender",
            sa.String(256),
            sa.ForeignKey("users.payment_profiles.id"),
            nullable=False,
        ),
        sa.Column(
            "receiver",
            sa.String(256),
            sa.ForeignKey("users.payment_profiles.id"),
            nullable=False,
        ),
        sa.Column("amount", sa.Float, nullable=False),
        sa.Column("title", sa.String(256), nullable=True),
        sa.Column("description", sa.String(256), nullable=True),
        sa.Column("sender_signiture", sa.String(256), nullable=True),
        sa.Column("receiver_signiture", sa.String(256), nullable=True),
        sa.Column(
            "transaction_status",
            sa.Enum(TransactionStatus, name="transaction_status"),
            nullable=False,
            default=TransactionStatus.DRAFT,
        ),
        sa.Column("salt_value", sa.String(256), nullable=False),
        sa.Column(
            "created_date",
            sa.DateTime,
            default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_date",
            sa.DateTime,
            default=sa.text("CURRENT_TIMESTAMP"),
            onupdate=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        schema="blockchain",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions", schema="blockchain")
    op.execute("DROP TYPE IF EXISTS transaction_status CASCADE")
    op.execute("DROP SCHEMA IF EXISTS blockchain")
    # ### end Alembic commands ###
