"""added payment profiles model

Revision ID: e2e01ce996d0
Revises: 86a881d7f966
Create Date: 2024-04-02 18:50:40.030410

"""

from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa

from lib.utils.constants.users import Status

# revision identifiers, used by Alembic.
revision: str = "e2e01ce996d0"
down_revision: Union[str, None] = "86a881d7f966"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_profiles",
        sa.Column("id", sa.UUID(as_uuid=True), primary_key=True),
        sa.Column("payment_id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "account_id", sa.UUID(as_uuid=True), sa.ForeignKey("users.accounts.id"), nullable=False
        ),
        sa.Column("card_id", sa.UUID(as_uuid=True), sa.ForeignKey("warehouse.cards.id"), nullable=False),
        sa.Column(
            "name", sa.String(256), nullable=False, default="New Payment Account."
        ),
        sa.Column(
            "description",
            sa.String(256),
            nullable=False,
            default="New Payment Account Created for Block Chain Transactions.",
        ),
        sa.Column("balance", sa.Float, default=0.0, nullable=False),
        sa.Column("created_date", sa.DateTime, default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column(
            "updated_date",
            sa.DateTime,
            default=sa.text("CURRENT_TIMESTAMP"),
            onupdate=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(Status, name="payment_status"),
            default=Status.NEW, nullable=False
        ),
        schema="users",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_profiles", schema="users")
    op.execute("DROP TYPE IF EXISTS payment_status CASCADE")
    # ### end Alembic commands ###
