"""added salting

Revision ID: 3a200fd2238a
Revises: 3c6f90022c25
Create Date: 2024-03-14 18:32:13.790632

"""
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a200fd2238a'
down_revision: Union[str, None] = '3c6f90022c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt_value', sa.String(256)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt_value')
    # ### end Alembic commands ###
