"""added payment infomation

Revision ID: b58f01440ae4
Revises: 05579a2b9e48
Create Date: 2024-03-27 19:24:31.658402

"""

from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from lib.utils.constants.users import AccountPaymentType

# revision identifiers, used by Alembic.
revision: str = "b58f01440ae4"
down_revision: Union[str, None] = "05579a2b9e48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_information",
        sa.Column(
            "id",
            sa.String(256),
            default=sa.text(f"'{str(uuid4())}'"),
            unique=True,
            nullable=False,
            primary_key=True,
        ),
        sa.Column(
            "payment_id",
            sa.String(256),
            default=sa.text(f"'{str(uuid4())}'"),
            unique=True,
            nullable=False,
        ),
        sa.Column(
            "account_id",
            sa.String(256),
            sa.ForeignKey("accounts.account_id"),
            nullable=False,
        ),
        sa.Column(
            "card_information",
            sa.String(256),
            sa.ForeignKey("account_cards.card_id"),
        ),
        sa.Column(
            "created_date",
            sa.DateTime,
            default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "expiration_date",
            sa.DateTime,
            default=sa.func.date_add(sa.func.now(), sa.func.text("INTERVAL 5 YEAR")),
        ),
        sa.Column("billing_address", sa.JSON, nullable=False),
        sa.Column(
            "account_type",
            sa.Enum(AccountPaymentType, name="paymenttype"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_information")
    # ### end Alembic commands ###
