version: '3.12'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: py_coin_db
      POSTGRES_USER: py_user
      POSTGRES_PASSWORD: py_user_password
    ports:
      - '5433:5432'

  migrations:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: py_coin_db
      POSTGRES_USER: py_user
      POSTGRES_PASSWORD: py_user_password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
        
    