version: '3.10'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: py_coin_test_db
      POSTGRES_USER: py_user_test
      POSTGRES_PASSWORD: py_user_test_password
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrations:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./db:/app/db
    command: bash -c "export PYTHONPATH=$PYTHONPATH:${pwd}; ./db/test_db_migration.sh"
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: py_coin_db
      POSTGRES_USER: py_user
      POSTGRES_PASSWORD: py_user_password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
        
volumes:
  postgres_data: