name: Python application

on:
  push:
    branches: ["release/Production", "release/UAT", "release/Development"]
  pull_request:
    branches: ["release/Production", "release/UAT", "release/Development"]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: py_coin_db
          POSTGRES_USER: py_user
          POSTGRES_PASSWORD: py_user_password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    env:
      TEST_RESULTS: /tmp/test-results

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Waiting for Postgres to be ready
        run: |
          for i in $(seq 1 10); do
            nc -z localhost 5432 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for PostgreSQL && exit 1

      - name: Run Linting
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pylint .

      - name: Run Type-Checking
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          mypy .

      - name: Run Unit Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          cp test.env .env
          source .env
          alembic upgrade head
          pytest .
  